# Generated by Django 5.0.3 on 2024-03-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0002_rename_name_subject_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='students',
        ),
    ]
