# Generated by Django 5.0.3 on 2024-03-28 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_app', '0002_alter_grade_grade'),
        ('student_app', '0013_student_subjects'),
        ('subject_app', '0003_remove_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='a_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='subject_app.subject'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='student_app.student'),
        ),
    ]
