# Generated by Django 5.0.3 on 2024-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=255)),
                ('personal_email', models.EmailField(max_length=255)),
                ('locker_number', models.IntegerField(max_length=5)),
                ('locker_combonation', models.CharField(max_length=8)),
            ],
        ),
    ]
