# Generated by Django 5.0.3 on 2024-03-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_alter_student_personal_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='locker_combonation',
            new_name='locker_combination',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
